# Generated by Django 5.2.8 on 2025-11-13 07:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='产品名称')),
                ('description', models.TextField(verbose_name='产品详情')),
                ('productType', models.CharField(choices=[('robot', '牛客'), ('monitor', '学校oj'), ('face', 'vjudge')], max_length=50, verbose_name='算法平台类型')),
                ('price', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='价格')),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '算法平台产品',
                'verbose_name_plural': '算法平台产品',
                'ordering': ('-publishDate',),
            },
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='Product/', verbose_name='产品图片')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productImgs', to='productsApp.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品图片',
                'verbose_name_plural': '产品图片',
            },
        ),
    ]
