# Generated by Django 5.2.8 on 2025-11-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0002_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2025-11-20', max_length=20, verbose_name='出生日期'),
        ),
    ]
