# Generated by Django 5.2.8 on 2025-12-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0003_alter_resume_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2025-12-22', max_length=20, verbose_name='出生日期'),
        ),
    ]
